using Wms.Domain.Entities.Common;
using Wms.Domain.Entities.Production;

namespace Wms.Domain.Entities.ProductionTransfer;

public sealed class PtHeader : BaseHeaderEntity
{
    public string? CustomerCode { get; set; }
    public long? CustomerId { get; set; }
    public string? SourceWarehouse { get; set; }
    public long? SourceWarehouseId { get; set; }
    public string? TargetWarehouse { get; set; }
    public long? TargetWarehouseId { get; set; }
    public long? ProductionHeaderId { get; set; }
    public PrHeader? ProductionHeader { get; set; }
    public long? ProductionOrderId { get; set; }
    public PrOrder? ProductionOrder { get; set; }
    public string TransferPurpose { get; set; } = "MaterialSupply";
    public bool TriggeredByProduction { get; set; }
    public bool AutoGenerated { get; set; }
    public bool RequiredForOrderStart { get; set; }
    public bool RequiredForOrderCompletion { get; set; }
    public long? SourceWorkcenterId { get; set; }
    public long? TargetWorkcenterId { get; set; }
    public ICollection<PtLine> Lines { get; set; } = new List<PtLine>();
    public ICollection<PtImportLine> ImportLines { get; set; } = new List<PtImportLine>();
}
