using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Wms.Application.Common;
using Wms.Application.Identity.Dtos;
using Wms.Application.Identity.Services;

namespace Wms.WebApi.Controllers.Identity;

[ApiController]
[Route("api/[controller]")]
[Authorize]
public sealed class UserDetailController : ControllerBase
{
    private readonly IUserDetailService _service; private readonly ICurrentUserAccessor _currentUser; private readonly ILocalizationService _localization; private readonly IFileUploadService _fileUploadService;
    public UserDetailController(IUserDetailService service, ICurrentUserAccessor currentUser, ILocalizationService localization, IFileUploadService fileUploadService) { _service = service; _currentUser = currentUser; _localization = localization; _fileUploadService = fileUploadService; }
    [HttpGet("{id:long}")] public async Task<ActionResult<ApiResponse<UserDetailDto>>> GetById(long id, CancellationToken cancellationToken = default) { var r = await _service.GetByIdAsync(id, cancellationToken); return StatusCode(r.StatusCode, r); }
    [HttpGet("user/{userId:long}")] public async Task<ActionResult<ApiResponse<UserDetailDto>>> GetByUserId(long userId, CancellationToken cancellationToken = default) { var r = await _service.GetByUserIdAsync(userId, cancellationToken); return StatusCode(r.StatusCode, r); }
    [HttpGet("current")] public async Task<ActionResult<ApiResponse<UserDetailDto>>> GetCurrent(CancellationToken cancellationToken = default) { var userId = _currentUser.UserId; if (!userId.HasValue) return StatusCode(401, ApiResponse<UserDetailDto>.ErrorResult(_localization.GetLocalizedString("Unauthorized"), _localization.GetLocalizedString("CurrentUserIdNotFoundInToken"), 401)); var r = await _service.GetByUserIdAsync(userId.Value, cancellationToken); if (r.StatusCode == 404) return Ok(ApiResponse<UserDetailDto>.SuccessResult(null!, _localization.GetLocalizedString("UserDetailNotFoundCanCreate"))); return StatusCode(r.StatusCode, r); }
    [HttpGet] public async Task<IActionResult> Get([FromQuery] PagedRequest request, CancellationToken cancellationToken = default) { var r = await _service.GetPagedAsync(request, cancellationToken); return StatusCode(r.StatusCode, r); }
    [HttpPost("paged")] public async Task<ActionResult<ApiResponse<PagedResponse<UserDetailDto>>>> GetPaged([FromBody] PagedRequest request, CancellationToken cancellationToken = default) { var r = await _service.GetPagedAsync(request, cancellationToken); return StatusCode(r.StatusCode, r); }
    [HttpPost] public async Task<ActionResult<ApiResponse<UserDetailDto>>> Create([FromBody] CreateUserDetailDto dto, CancellationToken cancellationToken = default) { var r = await _service.CreateAsync(dto, cancellationToken); return StatusCode(r.StatusCode, r); }
    [HttpPut("{id:long}")] public async Task<ActionResult<ApiResponse<UserDetailDto>>> Update(long id, [FromBody] UpdateUserDetailDto dto, CancellationToken cancellationToken = default) { var r = await _service.UpdateAsync(id, dto, cancellationToken); return StatusCode(r.StatusCode, r); }
    [HttpPut("current")] public async Task<ActionResult<ApiResponse<UserDetailDto>>> UpdateCurrent([FromBody] UpdateUserDetailDto dto, CancellationToken cancellationToken = default) { var userId = _currentUser.UserId; if (!userId.HasValue) return StatusCode(401, ApiResponse<UserDetailDto>.ErrorResult(_localization.GetLocalizedString("Unauthorized"), _localization.GetLocalizedString("CurrentUserIdNotFoundInToken"), 401)); var existing = await _service.GetByUserIdAsync(userId.Value, cancellationToken); if (existing.StatusCode == 404) return StatusCode((await _service.CreateAsync(new CreateUserDetailDto { UserId = userId.Value, ProfilePictureUrl = dto.ProfilePictureUrl, Height = dto.Height, Weight = dto.Weight, Description = dto.Description, Gender = dto.Gender }, cancellationToken)).StatusCode, await _service.CreateAsync(new CreateUserDetailDto { UserId = userId.Value, ProfilePictureUrl = dto.ProfilePictureUrl, Height = dto.Height, Weight = dto.Weight, Description = dto.Description, Gender = dto.Gender }, cancellationToken)); var r = await _service.UpdateAsync(existing.Data!.Id, dto, cancellationToken); return StatusCode(r.StatusCode, r); }
    [HttpDelete("{id:long}")] public async Task<ActionResult<ApiResponse<bool>>> Delete(long id, CancellationToken cancellationToken = default) { var r = await _service.DeleteAsync(id, cancellationToken); return StatusCode(r.StatusCode, r); }
    [HttpPost("upload-profile-picture")] public async Task<ActionResult<ApiResponse<string>>> UploadProfilePicture(IFormFile file, CancellationToken cancellationToken = default) { var userId = _currentUser.UserId; if (!userId.HasValue) return StatusCode(401, ApiResponse<string>.ErrorResult(_localization.GetLocalizedString("Unauthorized"), _localization.GetLocalizedString("CurrentUserIdNotFoundInToken"), 401)); var upload = await _fileUploadService.UploadProfilePictureAsync(file, userId.Value, cancellationToken); if (!upload.Success || string.IsNullOrWhiteSpace(upload.Data)) return StatusCode(upload.StatusCode, upload); var existing = await _service.GetByUserIdAsync(userId.Value, cancellationToken); if (existing.StatusCode == 404) await _service.CreateAsync(new CreateUserDetailDto { UserId = userId.Value, ProfilePictureUrl = upload.Data }, cancellationToken); else await _service.UpdateAsync(existing.Data!.Id, new UpdateUserDetailDto { ProfilePictureUrl = upload.Data }, cancellationToken); return StatusCode(upload.StatusCode, upload); }
}
