using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Wms.Shared.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class RefactorProductionSchemaAndLinkProductionTransfer : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "BarcodeGroup",
                table: "RII_BARCODE_DEFINITION");

            migrationBuilder.DropColumn(
                name: "ErpModule",
                table: "RII_BARCODE_DEFINITION");

            migrationBuilder.DropColumn(
                name: "ErpMovementType",
                table: "RII_BARCODE_DEFINITION");

            migrationBuilder.DropColumn(
                name: "ErpWarehouseCode",
                table: "RII_BARCODE_DEFINITION");

            migrationBuilder.RenameColumn(
                name: "Format",
                table: "RII_BARCODE_DEFINITION",
                newName: "SegmentPattern");

            migrationBuilder.RenameColumn(
                name: "EnableErpFallback",
                table: "RII_BARCODE_DEFINITION",
                newName: "AllowMirrorLookup");

            migrationBuilder.AddColumn<long>(
                name: "PrOperationLineId",
                table: "RII_PT_LINE_SERIAL",
                type: "bigint",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "LineRole",
                table: "RII_PT_LINE",
                type: "nvarchar(20)",
                maxLength: 20,
                nullable: true);

            migrationBuilder.AddColumn<long>(
                name: "ProductionOrderConsumptionId",
                table: "RII_PT_LINE",
                type: "bigint",
                nullable: true);

            migrationBuilder.AddColumn<long>(
                name: "ProductionOrderId",
                table: "RII_PT_LINE",
                type: "bigint",
                nullable: true);

            migrationBuilder.AddColumn<long>(
                name: "ProductionOrderOutputId",
                table: "RII_PT_LINE",
                type: "bigint",
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "RequiredQuantityFromProduction",
                table: "RII_PT_LINE",
                type: "decimal(18,6)",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "AutoGenerated",
                table: "RII_PT_HEADER",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<long>(
                name: "ProductionHeaderId",
                table: "RII_PT_HEADER",
                type: "bigint",
                nullable: true);

            migrationBuilder.AddColumn<long>(
                name: "ProductionOrderId",
                table: "RII_PT_HEADER",
                type: "bigint",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "RequiredForOrderCompletion",
                table: "RII_PT_HEADER",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "RequiredForOrderStart",
                table: "RII_PT_HEADER",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<long>(
                name: "SourceWorkcenterId",
                table: "RII_PT_HEADER",
                type: "bigint",
                nullable: true);

            migrationBuilder.AddColumn<long>(
                name: "TargetWorkcenterId",
                table: "RII_PT_HEADER",
                type: "bigint",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "TransferPurpose",
                table: "RII_PT_HEADER",
                type: "nvarchar(30)",
                maxLength: 30,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<bool>(
                name: "TriggeredByProduction",
                table: "RII_PT_HEADER",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<DateTime>(
                name: "ActualEndDate",
                table: "RII_PR_HEADER",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "ActualStartDate",
                table: "RII_PR_HEADER",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "CompletedQuantity",
                table: "RII_PR_HEADER",
                type: "decimal(18,6)",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "ExecutionMode",
                table: "RII_PR_HEADER",
                type: "nvarchar(20)",
                maxLength: 20,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "MainStockCode",
                table: "RII_PR_HEADER",
                type: "nvarchar(50)",
                maxLength: 50,
                nullable: true);

            migrationBuilder.AddColumn<long>(
                name: "MainStockId",
                table: "RII_PR_HEADER",
                type: "bigint",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "MainYapKod",
                table: "RII_PR_HEADER",
                type: "nvarchar(50)",
                maxLength: 50,
                nullable: true);

            migrationBuilder.AddColumn<long>(
                name: "MainYapKodId",
                table: "RII_PR_HEADER",
                type: "bigint",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "PlanType",
                table: "RII_PR_HEADER",
                type: "nvarchar(20)",
                maxLength: 20,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<DateTime>(
                name: "PlannedEndDate",
                table: "RII_PR_HEADER",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "PlannedQuantity",
                table: "RII_PR_HEADER",
                type: "decimal(18,6)",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "PlannedStartDate",
                table: "RII_PR_HEADER",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "Priority",
                table: "RII_PR_HEADER",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<long>(
                name: "ProjectId",
                table: "RII_PR_HEADER",
                type: "bigint",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "ReleasedAt",
                table: "RII_PR_HEADER",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<long>(
                name: "ReleasedBy",
                table: "RII_PR_HEADER",
                type: "bigint",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Status",
                table: "RII_PR_HEADER",
                type: "nvarchar(20)",
                maxLength: 20,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "DefinitionType",
                table: "RII_BARCODE_DEFINITION",
                type: "nvarchar(50)",
                maxLength: 50,
                nullable: false,
                defaultValue: "pattern");

            migrationBuilder.AddColumn<string>(
                name: "RequiredSegments",
                table: "RII_BARCODE_DEFINITION",
                type: "nvarchar(250)",
                maxLength: 250,
                nullable: true);

            migrationBuilder.CreateTable(
                name: "RII_PR_HEADER_ASSIGNMENT",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    HeaderId = table.Column<long>(type: "bigint", nullable: false),
                    AssignedUserId = table.Column<long>(type: "bigint", nullable: true),
                    AssignedRoleId = table.Column<long>(type: "bigint", nullable: true),
                    AssignedTeamId = table.Column<long>(type: "bigint", nullable: true),
                    AssignmentType = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    AssignedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    AcceptedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsActive = table.Column<bool>(type: "bit", nullable: false),
                    BranchCode = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false, defaultValue: "0"),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    CreatedBy = table.Column<long>(type: "bigint", nullable: true),
                    UpdatedBy = table.Column<long>(type: "bigint", nullable: true),
                    DeletedBy = table.Column<long>(type: "bigint", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RII_PR_HEADER_ASSIGNMENT", x => x.Id);
                    table.ForeignKey(
                        name: "FK_RII_PR_HEADER_ASSIGNMENT_RII_PR_HEADER_HeaderId",
                        column: x => x.HeaderId,
                        principalTable: "RII_PR_HEADER",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "RII_PR_ORDER",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    HeaderId = table.Column<long>(type: "bigint", nullable: false),
                    OrderNo = table.Column<string>(type: "nvarchar(30)", maxLength: 30, nullable: false),
                    OrderDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Description = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    OrderType = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    Status = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    Priority = table.Column<int>(type: "int", nullable: false),
                    SequenceNo = table.Column<int>(type: "int", nullable: true),
                    ParallelGroupNo = table.Column<int>(type: "int", nullable: true),
                    ProducedStockId = table.Column<long>(type: "bigint", nullable: false),
                    ProducedStockCode = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    ProducedYapKodId = table.Column<long>(type: "bigint", nullable: true),
                    ProducedYapKod = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    PlannedQuantity = table.Column<decimal>(type: "decimal(18,6)", nullable: false),
                    StartedQuantity = table.Column<decimal>(type: "decimal(18,6)", nullable: true),
                    CompletedQuantity = table.Column<decimal>(type: "decimal(18,6)", nullable: true),
                    ScrapQuantity = table.Column<decimal>(type: "decimal(18,6)", nullable: true),
                    SourceWarehouseId = table.Column<long>(type: "bigint", nullable: true),
                    SourceWarehouseCode = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    TargetWarehouseId = table.Column<long>(type: "bigint", nullable: true),
                    TargetWarehouseCode = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    CanStartManually = table.Column<bool>(type: "bit", nullable: false),
                    AutoStartWhenDependenciesDone = table.Column<bool>(type: "bit", nullable: false),
                    IsTransferRequiredBeforeStart = table.Column<bool>(type: "bit", nullable: false),
                    PlannedStartDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    PlannedEndDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    ActualStartDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    ActualEndDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    BlockedReason = table.Column<string>(type: "nvarchar(250)", maxLength: 250, nullable: true),
                    StatusNote = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    BranchCode = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false, defaultValue: "0"),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    CreatedBy = table.Column<long>(type: "bigint", nullable: true),
                    UpdatedBy = table.Column<long>(type: "bigint", nullable: true),
                    DeletedBy = table.Column<long>(type: "bigint", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RII_PR_ORDER", x => x.Id);
                    table.ForeignKey(
                        name: "FK_RII_PR_ORDER_RII_PR_HEADER_HeaderId",
                        column: x => x.HeaderId,
                        principalTable: "RII_PR_HEADER",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "RII_PR_OPERATION",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    OrderId = table.Column<long>(type: "bigint", nullable: false),
                    OperationNo = table.Column<string>(type: "nvarchar(30)", maxLength: 30, nullable: true),
                    OperationType = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    Status = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    WorkcenterId = table.Column<long>(type: "bigint", nullable: true),
                    MachineId = table.Column<long>(type: "bigint", nullable: true),
                    ExecutedByUserId = table.Column<long>(type: "bigint", nullable: true),
                    StartedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    CompletedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    PlannedDurationMinutes = table.Column<int>(type: "int", nullable: true),
                    ActualDurationMinutes = table.Column<int>(type: "int", nullable: true),
                    PauseDurationMinutes = table.Column<int>(type: "int", nullable: true),
                    NetWorkingDurationMinutes = table.Column<int>(type: "int", nullable: true),
                    Description = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    BranchCode = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false, defaultValue: "0"),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    CreatedBy = table.Column<long>(type: "bigint", nullable: true),
                    UpdatedBy = table.Column<long>(type: "bigint", nullable: true),
                    DeletedBy = table.Column<long>(type: "bigint", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RII_PR_OPERATION", x => x.Id);
                    table.ForeignKey(
                        name: "FK_RII_PR_OPERATION_RII_PR_ORDER_OrderId",
                        column: x => x.OrderId,
                        principalTable: "RII_PR_ORDER",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "RII_PR_ORDER_ASSIGNMENT",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    OrderId = table.Column<long>(type: "bigint", nullable: false),
                    AssignedUserId = table.Column<long>(type: "bigint", nullable: true),
                    AssignedRoleId = table.Column<long>(type: "bigint", nullable: true),
                    AssignedTeamId = table.Column<long>(type: "bigint", nullable: true),
                    AssignmentType = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    AssignedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    AcceptedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    CompletedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsActive = table.Column<bool>(type: "bit", nullable: false),
                    Note = table.Column<string>(type: "nvarchar(250)", maxLength: 250, nullable: true),
                    BranchCode = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false, defaultValue: "0"),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    CreatedBy = table.Column<long>(type: "bigint", nullable: true),
                    UpdatedBy = table.Column<long>(type: "bigint", nullable: true),
                    DeletedBy = table.Column<long>(type: "bigint", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RII_PR_ORDER_ASSIGNMENT", x => x.Id);
                    table.ForeignKey(
                        name: "FK_RII_PR_ORDER_ASSIGNMENT_RII_PR_ORDER_OrderId",
                        column: x => x.OrderId,
                        principalTable: "RII_PR_ORDER",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "RII_PR_ORDER_CONSUMPTION",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    OrderId = table.Column<long>(type: "bigint", nullable: false),
                    SequenceNo = table.Column<int>(type: "int", nullable: true),
                    StockId = table.Column<long>(type: "bigint", nullable: false),
                    StockCode = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    YapKodId = table.Column<long>(type: "bigint", nullable: true),
                    YapKod = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    Unit = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    PlannedQuantity = table.Column<decimal>(type: "decimal(18,6)", nullable: false),
                    ConsumedQuantity = table.Column<decimal>(type: "decimal(18,6)", nullable: true),
                    TrackingMode = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    SerialEntryMode = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    SourceWarehouseId = table.Column<long>(type: "bigint", nullable: true),
                    SourceWarehouseCode = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    SourceCellCode = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    IsBackflush = table.Column<bool>(type: "bit", nullable: false),
                    IsMandatory = table.Column<bool>(type: "bit", nullable: false),
                    Status = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    BranchCode = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false, defaultValue: "0"),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    CreatedBy = table.Column<long>(type: "bigint", nullable: true),
                    UpdatedBy = table.Column<long>(type: "bigint", nullable: true),
                    DeletedBy = table.Column<long>(type: "bigint", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RII_PR_ORDER_CONSUMPTION", x => x.Id);
                    table.ForeignKey(
                        name: "FK_RII_PR_ORDER_CONSUMPTION_RII_PR_ORDER_OrderId",
                        column: x => x.OrderId,
                        principalTable: "RII_PR_ORDER",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "RII_PR_ORDER_DEPENDENCY",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    HeaderId = table.Column<long>(type: "bigint", nullable: false),
                    PredecessorOrderId = table.Column<long>(type: "bigint", nullable: false),
                    SuccessorOrderId = table.Column<long>(type: "bigint", nullable: false),
                    DependencyType = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    IsRequired = table.Column<bool>(type: "bit", nullable: false),
                    LagMinutes = table.Column<int>(type: "int", nullable: false),
                    RequiredTransferCompleted = table.Column<bool>(type: "bit", nullable: false),
                    RequiredOutputAvailable = table.Column<bool>(type: "bit", nullable: false),
                    ConditionNote = table.Column<string>(type: "nvarchar(250)", maxLength: 250, nullable: true),
                    BranchCode = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false, defaultValue: "0"),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    CreatedBy = table.Column<long>(type: "bigint", nullable: true),
                    UpdatedBy = table.Column<long>(type: "bigint", nullable: true),
                    DeletedBy = table.Column<long>(type: "bigint", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RII_PR_ORDER_DEPENDENCY", x => x.Id);
                    table.ForeignKey(
                        name: "FK_RII_PR_ORDER_DEPENDENCY_RII_PR_HEADER_HeaderId",
                        column: x => x.HeaderId,
                        principalTable: "RII_PR_HEADER",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_RII_PR_ORDER_DEPENDENCY_RII_PR_ORDER_PredecessorOrderId",
                        column: x => x.PredecessorOrderId,
                        principalTable: "RII_PR_ORDER",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_RII_PR_ORDER_DEPENDENCY_RII_PR_ORDER_SuccessorOrderId",
                        column: x => x.SuccessorOrderId,
                        principalTable: "RII_PR_ORDER",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "RII_PR_ORDER_OUTPUT",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    OrderId = table.Column<long>(type: "bigint", nullable: false),
                    SequenceNo = table.Column<int>(type: "int", nullable: true),
                    StockId = table.Column<long>(type: "bigint", nullable: false),
                    StockCode = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    YapKodId = table.Column<long>(type: "bigint", nullable: true),
                    YapKod = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    Unit = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    PlannedQuantity = table.Column<decimal>(type: "decimal(18,6)", nullable: false),
                    ProducedQuantity = table.Column<decimal>(type: "decimal(18,6)", nullable: true),
                    TrackingMode = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    SerialEntryMode = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    TargetWarehouseId = table.Column<long>(type: "bigint", nullable: true),
                    TargetWarehouseCode = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    TargetCellCode = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    Status = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    BranchCode = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false, defaultValue: "0"),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    CreatedBy = table.Column<long>(type: "bigint", nullable: true),
                    UpdatedBy = table.Column<long>(type: "bigint", nullable: true),
                    DeletedBy = table.Column<long>(type: "bigint", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RII_PR_ORDER_OUTPUT", x => x.Id);
                    table.ForeignKey(
                        name: "FK_RII_PR_ORDER_OUTPUT_RII_PR_ORDER_OrderId",
                        column: x => x.OrderId,
                        principalTable: "RII_PR_ORDER",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "RII_PR_OPERATION_EVENT",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    OperationId = table.Column<long>(type: "bigint", nullable: false),
                    OrderId = table.Column<long>(type: "bigint", nullable: false),
                    EventType = table.Column<string>(type: "nvarchar(30)", maxLength: 30, nullable: false),
                    EventReasonCode = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    EventNote = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    EventAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    DurationMinutes = table.Column<int>(type: "int", nullable: true),
                    PerformedByUserId = table.Column<long>(type: "bigint", nullable: true),
                    WorkcenterId = table.Column<long>(type: "bigint", nullable: true),
                    MachineId = table.Column<long>(type: "bigint", nullable: true),
                    BranchCode = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false, defaultValue: "0"),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    CreatedBy = table.Column<long>(type: "bigint", nullable: true),
                    UpdatedBy = table.Column<long>(type: "bigint", nullable: true),
                    DeletedBy = table.Column<long>(type: "bigint", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RII_PR_OPERATION_EVENT", x => x.Id);
                    table.ForeignKey(
                        name: "FK_RII_PR_OPERATION_EVENT_RII_PR_OPERATION_OperationId",
                        column: x => x.OperationId,
                        principalTable: "RII_PR_OPERATION",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_RII_PR_OPERATION_EVENT_RII_PR_ORDER_OrderId",
                        column: x => x.OrderId,
                        principalTable: "RII_PR_ORDER",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "RII_PR_OPERATION_LINE",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    OperationId = table.Column<long>(type: "bigint", nullable: false),
                    OrderId = table.Column<long>(type: "bigint", nullable: false),
                    LineRole = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    OrderOutputId = table.Column<long>(type: "bigint", nullable: true),
                    OrderConsumptionId = table.Column<long>(type: "bigint", nullable: true),
                    StockId = table.Column<long>(type: "bigint", nullable: false),
                    StockCode = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    YapKodId = table.Column<long>(type: "bigint", nullable: true),
                    YapKod = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    Quantity = table.Column<decimal>(type: "decimal(18,6)", nullable: false),
                    Unit = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    SerialNo1 = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    SerialNo2 = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    SerialNo3 = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    SerialNo4 = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    LotNo = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    BatchNo = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    SourceWarehouseId = table.Column<long>(type: "bigint", nullable: true),
                    SourceWarehouseCode = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    TargetWarehouseId = table.Column<long>(type: "bigint", nullable: true),
                    TargetWarehouseCode = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    SourceCellCode = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    TargetCellCode = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    ScannedBarcode = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    BranchCode = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false, defaultValue: "0"),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    CreatedBy = table.Column<long>(type: "bigint", nullable: true),
                    UpdatedBy = table.Column<long>(type: "bigint", nullable: true),
                    DeletedBy = table.Column<long>(type: "bigint", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RII_PR_OPERATION_LINE", x => x.Id);
                    table.ForeignKey(
                        name: "FK_RII_PR_OPERATION_LINE_RII_PR_OPERATION_OperationId",
                        column: x => x.OperationId,
                        principalTable: "RII_PR_OPERATION",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_RII_PR_OPERATION_LINE_RII_PR_ORDER_CONSUMPTION_OrderConsumptionId",
                        column: x => x.OrderConsumptionId,
                        principalTable: "RII_PR_ORDER_CONSUMPTION",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_RII_PR_OPERATION_LINE_RII_PR_ORDER_OUTPUT_OrderOutputId",
                        column: x => x.OrderOutputId,
                        principalTable: "RII_PR_ORDER_OUTPUT",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_RII_PR_OPERATION_LINE_RII_PR_ORDER_OrderId",
                        column: x => x.OrderId,
                        principalTable: "RII_PR_ORDER",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_RII_PT_LINE_SERIAL_PrOperationLineId",
                table: "RII_PT_LINE_SERIAL",
                column: "PrOperationLineId");

            migrationBuilder.CreateIndex(
                name: "IX_RII_PT_LINE_ProductionOrderConsumptionId",
                table: "RII_PT_LINE",
                column: "ProductionOrderConsumptionId");

            migrationBuilder.CreateIndex(
                name: "IX_RII_PT_LINE_ProductionOrderId",
                table: "RII_PT_LINE",
                column: "ProductionOrderId");

            migrationBuilder.CreateIndex(
                name: "IX_RII_PT_LINE_ProductionOrderOutputId",
                table: "RII_PT_LINE",
                column: "ProductionOrderOutputId");

            migrationBuilder.CreateIndex(
                name: "IX_PtHeader_ProductionHeaderId",
                table: "RII_PT_HEADER",
                column: "ProductionHeaderId");

            migrationBuilder.CreateIndex(
                name: "IX_PtHeader_ProductionOrderId",
                table: "RII_PT_HEADER",
                column: "ProductionOrderId");

            migrationBuilder.CreateIndex(
                name: "IX_PrHeader_MainStockId",
                table: "RII_PR_HEADER",
                column: "MainStockId");

            migrationBuilder.CreateIndex(
                name: "IX_PrHeader_MainYapKodId",
                table: "RII_PR_HEADER",
                column: "MainYapKodId");

            migrationBuilder.CreateIndex(
                name: "IX_PrHeader_ProjectId",
                table: "RII_PR_HEADER",
                column: "ProjectId");

            migrationBuilder.CreateIndex(
                name: "IX_PrHeaderAssignment_HeaderId_IsActive",
                table: "RII_PR_HEADER_ASSIGNMENT",
                columns: new[] { "HeaderId", "IsActive" });

            migrationBuilder.CreateIndex(
                name: "IX_PrOperation_OrderId_Status",
                table: "RII_PR_OPERATION",
                columns: new[] { "OrderId", "Status" });

            migrationBuilder.CreateIndex(
                name: "IX_PrOperationEvent_OrderId_EventAt",
                table: "RII_PR_OPERATION_EVENT",
                columns: new[] { "OrderId", "EventAt" });

            migrationBuilder.CreateIndex(
                name: "IX_RII_PR_OPERATION_EVENT_OperationId",
                table: "RII_PR_OPERATION_EVENT",
                column: "OperationId");

            migrationBuilder.CreateIndex(
                name: "IX_PrOperationLine_OrderId",
                table: "RII_PR_OPERATION_LINE",
                column: "OrderId");

            migrationBuilder.CreateIndex(
                name: "IX_RII_PR_OPERATION_LINE_OperationId",
                table: "RII_PR_OPERATION_LINE",
                column: "OperationId");

            migrationBuilder.CreateIndex(
                name: "IX_RII_PR_OPERATION_LINE_OrderConsumptionId",
                table: "RII_PR_OPERATION_LINE",
                column: "OrderConsumptionId");

            migrationBuilder.CreateIndex(
                name: "IX_RII_PR_OPERATION_LINE_OrderOutputId",
                table: "RII_PR_OPERATION_LINE",
                column: "OrderOutputId");

            migrationBuilder.CreateIndex(
                name: "IX_PrOrder_HeaderId_OrderNo",
                table: "RII_PR_ORDER",
                columns: new[] { "HeaderId", "OrderNo" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_PrOrder_HeaderId_Status",
                table: "RII_PR_ORDER",
                columns: new[] { "HeaderId", "Status" });

            migrationBuilder.CreateIndex(
                name: "IX_PrOrderAssignment_OrderId_IsActive",
                table: "RII_PR_ORDER_ASSIGNMENT",
                columns: new[] { "OrderId", "IsActive" });

            migrationBuilder.CreateIndex(
                name: "IX_PrOrderConsumption_OrderId",
                table: "RII_PR_ORDER_CONSUMPTION",
                column: "OrderId");

            migrationBuilder.CreateIndex(
                name: "IX_PrOrderDependency_HeaderId",
                table: "RII_PR_ORDER_DEPENDENCY",
                column: "HeaderId");

            migrationBuilder.CreateIndex(
                name: "IX_PrOrderDependency_Predecessor_Successor",
                table: "RII_PR_ORDER_DEPENDENCY",
                columns: new[] { "PredecessorOrderId", "SuccessorOrderId" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_RII_PR_ORDER_DEPENDENCY_SuccessorOrderId",
                table: "RII_PR_ORDER_DEPENDENCY",
                column: "SuccessorOrderId");

            migrationBuilder.CreateIndex(
                name: "IX_PrOrderOutput_OrderId",
                table: "RII_PR_ORDER_OUTPUT",
                column: "OrderId");

            migrationBuilder.AddForeignKey(
                name: "FK_RII_PT_HEADER_RII_PR_HEADER_ProductionHeaderId",
                table: "RII_PT_HEADER",
                column: "ProductionHeaderId",
                principalTable: "RII_PR_HEADER",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_RII_PT_HEADER_RII_PR_ORDER_ProductionOrderId",
                table: "RII_PT_HEADER",
                column: "ProductionOrderId",
                principalTable: "RII_PR_ORDER",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_RII_PT_LINE_RII_PR_ORDER_CONSUMPTION_ProductionOrderConsumptionId",
                table: "RII_PT_LINE",
                column: "ProductionOrderConsumptionId",
                principalTable: "RII_PR_ORDER_CONSUMPTION",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_RII_PT_LINE_RII_PR_ORDER_OUTPUT_ProductionOrderOutputId",
                table: "RII_PT_LINE",
                column: "ProductionOrderOutputId",
                principalTable: "RII_PR_ORDER_OUTPUT",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_RII_PT_LINE_RII_PR_ORDER_ProductionOrderId",
                table: "RII_PT_LINE",
                column: "ProductionOrderId",
                principalTable: "RII_PR_ORDER",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_RII_PT_LINE_SERIAL_RII_PR_OPERATION_LINE_PrOperationLineId",
                table: "RII_PT_LINE_SERIAL",
                column: "PrOperationLineId",
                principalTable: "RII_PR_OPERATION_LINE",
                principalColumn: "Id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_RII_PT_HEADER_RII_PR_HEADER_ProductionHeaderId",
                table: "RII_PT_HEADER");

            migrationBuilder.DropForeignKey(
                name: "FK_RII_PT_HEADER_RII_PR_ORDER_ProductionOrderId",
                table: "RII_PT_HEADER");

            migrationBuilder.DropForeignKey(
                name: "FK_RII_PT_LINE_RII_PR_ORDER_CONSUMPTION_ProductionOrderConsumptionId",
                table: "RII_PT_LINE");

            migrationBuilder.DropForeignKey(
                name: "FK_RII_PT_LINE_RII_PR_ORDER_OUTPUT_ProductionOrderOutputId",
                table: "RII_PT_LINE");

            migrationBuilder.DropForeignKey(
                name: "FK_RII_PT_LINE_RII_PR_ORDER_ProductionOrderId",
                table: "RII_PT_LINE");

            migrationBuilder.DropForeignKey(
                name: "FK_RII_PT_LINE_SERIAL_RII_PR_OPERATION_LINE_PrOperationLineId",
                table: "RII_PT_LINE_SERIAL");

            migrationBuilder.DropTable(
                name: "RII_PR_HEADER_ASSIGNMENT");

            migrationBuilder.DropTable(
                name: "RII_PR_OPERATION_EVENT");

            migrationBuilder.DropTable(
                name: "RII_PR_OPERATION_LINE");

            migrationBuilder.DropTable(
                name: "RII_PR_ORDER_ASSIGNMENT");

            migrationBuilder.DropTable(
                name: "RII_PR_ORDER_DEPENDENCY");

            migrationBuilder.DropTable(
                name: "RII_PR_OPERATION");

            migrationBuilder.DropTable(
                name: "RII_PR_ORDER_CONSUMPTION");

            migrationBuilder.DropTable(
                name: "RII_PR_ORDER_OUTPUT");

            migrationBuilder.DropTable(
                name: "RII_PR_ORDER");

            migrationBuilder.DropIndex(
                name: "IX_RII_PT_LINE_SERIAL_PrOperationLineId",
                table: "RII_PT_LINE_SERIAL");

            migrationBuilder.DropIndex(
                name: "IX_RII_PT_LINE_ProductionOrderConsumptionId",
                table: "RII_PT_LINE");

            migrationBuilder.DropIndex(
                name: "IX_RII_PT_LINE_ProductionOrderId",
                table: "RII_PT_LINE");

            migrationBuilder.DropIndex(
                name: "IX_RII_PT_LINE_ProductionOrderOutputId",
                table: "RII_PT_LINE");

            migrationBuilder.DropIndex(
                name: "IX_PtHeader_ProductionHeaderId",
                table: "RII_PT_HEADER");

            migrationBuilder.DropIndex(
                name: "IX_PtHeader_ProductionOrderId",
                table: "RII_PT_HEADER");

            migrationBuilder.DropIndex(
                name: "IX_PrHeader_MainStockId",
                table: "RII_PR_HEADER");

            migrationBuilder.DropIndex(
                name: "IX_PrHeader_MainYapKodId",
                table: "RII_PR_HEADER");

            migrationBuilder.DropIndex(
                name: "IX_PrHeader_ProjectId",
                table: "RII_PR_HEADER");

            migrationBuilder.DropColumn(
                name: "PrOperationLineId",
                table: "RII_PT_LINE_SERIAL");

            migrationBuilder.DropColumn(
                name: "LineRole",
                table: "RII_PT_LINE");

            migrationBuilder.DropColumn(
                name: "ProductionOrderConsumptionId",
                table: "RII_PT_LINE");

            migrationBuilder.DropColumn(
                name: "ProductionOrderId",
                table: "RII_PT_LINE");

            migrationBuilder.DropColumn(
                name: "ProductionOrderOutputId",
                table: "RII_PT_LINE");

            migrationBuilder.DropColumn(
                name: "RequiredQuantityFromProduction",
                table: "RII_PT_LINE");

            migrationBuilder.DropColumn(
                name: "AutoGenerated",
                table: "RII_PT_HEADER");

            migrationBuilder.DropColumn(
                name: "ProductionHeaderId",
                table: "RII_PT_HEADER");

            migrationBuilder.DropColumn(
                name: "ProductionOrderId",
                table: "RII_PT_HEADER");

            migrationBuilder.DropColumn(
                name: "RequiredForOrderCompletion",
                table: "RII_PT_HEADER");

            migrationBuilder.DropColumn(
                name: "RequiredForOrderStart",
                table: "RII_PT_HEADER");

            migrationBuilder.DropColumn(
                name: "SourceWorkcenterId",
                table: "RII_PT_HEADER");

            migrationBuilder.DropColumn(
                name: "TargetWorkcenterId",
                table: "RII_PT_HEADER");

            migrationBuilder.DropColumn(
                name: "TransferPurpose",
                table: "RII_PT_HEADER");

            migrationBuilder.DropColumn(
                name: "TriggeredByProduction",
                table: "RII_PT_HEADER");

            migrationBuilder.DropColumn(
                name: "ActualEndDate",
                table: "RII_PR_HEADER");

            migrationBuilder.DropColumn(
                name: "ActualStartDate",
                table: "RII_PR_HEADER");

            migrationBuilder.DropColumn(
                name: "CompletedQuantity",
                table: "RII_PR_HEADER");

            migrationBuilder.DropColumn(
                name: "ExecutionMode",
                table: "RII_PR_HEADER");

            migrationBuilder.DropColumn(
                name: "MainStockCode",
                table: "RII_PR_HEADER");

            migrationBuilder.DropColumn(
                name: "MainStockId",
                table: "RII_PR_HEADER");

            migrationBuilder.DropColumn(
                name: "MainYapKod",
                table: "RII_PR_HEADER");

            migrationBuilder.DropColumn(
                name: "MainYapKodId",
                table: "RII_PR_HEADER");

            migrationBuilder.DropColumn(
                name: "PlanType",
                table: "RII_PR_HEADER");

            migrationBuilder.DropColumn(
                name: "PlannedEndDate",
                table: "RII_PR_HEADER");

            migrationBuilder.DropColumn(
                name: "PlannedQuantity",
                table: "RII_PR_HEADER");

            migrationBuilder.DropColumn(
                name: "PlannedStartDate",
                table: "RII_PR_HEADER");

            migrationBuilder.DropColumn(
                name: "Priority",
                table: "RII_PR_HEADER");

            migrationBuilder.DropColumn(
                name: "ProjectId",
                table: "RII_PR_HEADER");

            migrationBuilder.DropColumn(
                name: "ReleasedAt",
                table: "RII_PR_HEADER");

            migrationBuilder.DropColumn(
                name: "ReleasedBy",
                table: "RII_PR_HEADER");

            migrationBuilder.DropColumn(
                name: "Status",
                table: "RII_PR_HEADER");

            migrationBuilder.DropColumn(
                name: "DefinitionType",
                table: "RII_BARCODE_DEFINITION");

            migrationBuilder.DropColumn(
                name: "RequiredSegments",
                table: "RII_BARCODE_DEFINITION");

            migrationBuilder.RenameColumn(
                name: "SegmentPattern",
                table: "RII_BARCODE_DEFINITION",
                newName: "Format");

            migrationBuilder.RenameColumn(
                name: "AllowMirrorLookup",
                table: "RII_BARCODE_DEFINITION",
                newName: "EnableErpFallback");

            migrationBuilder.AddColumn<string>(
                name: "BarcodeGroup",
                table: "RII_BARCODE_DEFINITION",
                type: "nvarchar(20)",
                maxLength: 20,
                nullable: false,
                defaultValue: "1");

            migrationBuilder.AddColumn<int>(
                name: "ErpModule",
                table: "RII_BARCODE_DEFINITION",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "ErpMovementType",
                table: "RII_BARCODE_DEFINITION",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "ErpWarehouseCode",
                table: "RII_BARCODE_DEFINITION",
                type: "int",
                nullable: false,
                defaultValue: 0);
        }
    }
}
