using AutoMapper;
using Microsoft.EntityFrameworkCore;
using Wms.Application.Common;
using Wms.Application.Identity.Dtos;
using Wms.Domain.Common;
using Wms.Domain.Entities.Identity;

namespace Wms.Application.Identity.Services;

public sealed class UserDetailService : IUserDetailService
{
    private readonly IRepository<UserDetail> _details; private readonly IRepository<User> _users; private readonly IUnitOfWork _uow; private readonly IMapper _mapper; private readonly ILocalizationService _loc;
    public UserDetailService(IRepository<UserDetail> details, IRepository<User> users, IUnitOfWork uow, IMapper mapper, ILocalizationService loc) { _details = details; _users = users; _uow = uow; _mapper = mapper; _loc = loc; }
    public async Task<ApiResponse<UserDetailDto>> GetByIdAsync(long id, CancellationToken cancellationToken = default) { var e = await _details.Query().FirstOrDefaultAsync(x => x.Id == id, cancellationToken); if (e == null || e.IsDeleted) { var m = _loc.GetLocalizedString("UserDetailNotFound"); return ApiResponse<UserDetailDto>.ErrorResult(m,m,404);} return ApiResponse<UserDetailDto>.SuccessResult(_mapper.Map<UserDetailDto>(e), _loc.GetLocalizedString("UserDetailRetrievedSuccessfully")); }
    public async Task<ApiResponse<UserDetailDto>> GetByUserIdAsync(long userId, CancellationToken cancellationToken = default) { var e = await _details.Query().FirstOrDefaultAsync(x => x.UserId == userId && !x.IsDeleted, cancellationToken); if (e == null) { var m = _loc.GetLocalizedString("UserDetailNotFound"); return ApiResponse<UserDetailDto>.ErrorResult(m,m,404);} return ApiResponse<UserDetailDto>.SuccessResult(_mapper.Map<UserDetailDto>(e), _loc.GetLocalizedString("UserDetailRetrievedSuccessfully")); }
    public async Task<ApiResponse<IEnumerable<UserDetailDto>>> GetAllAsync(CancellationToken cancellationToken = default) => ApiResponse<IEnumerable<UserDetailDto>>.SuccessResult(_mapper.Map<List<UserDetailDto>>(await _details.Query().Where(x => !x.IsDeleted).ToListAsync(cancellationToken)), _loc.GetLocalizedString("UserDetailRetrievedSuccessfully"));
    public async Task<ApiResponse<PagedResponse<UserDetailDto>>> GetPagedAsync(PagedRequest request, CancellationToken cancellationToken = default) { request ??= new(); var q = _details.Query().Where(x => !x.IsDeleted).ApplyFilters(request.Filters, request.FilterLogic).ApplySorting(request.SortBy ?? "Id", string.Equals(request.SortDirection,"desc",StringComparison.OrdinalIgnoreCase)); var total = await q.CountAsync(cancellationToken); var items = await q.ApplyPagination(request.PageNumber, request.PageSize).ToListAsync(cancellationToken); return ApiResponse<PagedResponse<UserDetailDto>>.SuccessResult(new(_mapper.Map<List<UserDetailDto>>(items), total, request.PageNumber < 1 ? 1 : request.PageNumber, request.PageSize < 1 ? 20 : request.PageSize), _loc.GetLocalizedString("UserDetailRetrievedSuccessfully")); }
    public async Task<ApiResponse<UserDetailDto>> CreateAsync(CreateUserDetailDto dto, CancellationToken cancellationToken = default) { var user = await _users.GetByIdAsync(dto.UserId, cancellationToken); if (user == null || user.IsDeleted) { var m = _loc.GetLocalizedString("UserNotFound"); return ApiResponse<UserDetailDto>.ErrorResult(m,m,404);} if (await _details.Query().AnyAsync(x => x.UserId == dto.UserId && !x.IsDeleted,cancellationToken)) { var m = _loc.GetLocalizedString("UserDetailAlreadyExists"); return ApiResponse<UserDetailDto>.ErrorResult(m,m,400);} var e = _mapper.Map<UserDetail>(dto); e.CreatedDate = DateTimeProvider.Now; await _details.AddAsync(e,cancellationToken); await _uow.SaveChangesAsync(cancellationToken); return ApiResponse<UserDetailDto>.SuccessResult(_mapper.Map<UserDetailDto>(e), _loc.GetLocalizedString("UserDetailCreatedSuccessfully")); }
    public async Task<ApiResponse<UserDetailDto>> UpdateAsync(long id, UpdateUserDetailDto dto, CancellationToken cancellationToken = default) { var e = await _details.Query(tracking:true).FirstOrDefaultAsync(x => x.Id == id, cancellationToken); if (e == null || e.IsDeleted) { var m = _loc.GetLocalizedString("UserDetailNotFound"); return ApiResponse<UserDetailDto>.ErrorResult(m,m,404);} _mapper.Map(dto,e); e.UpdatedDate = DateTimeProvider.Now; _details.Update(e); await _uow.SaveChangesAsync(cancellationToken); return ApiResponse<UserDetailDto>.SuccessResult(_mapper.Map<UserDetailDto>(e), _loc.GetLocalizedString("UserDetailUpdatedSuccessfully")); }
    public async Task<ApiResponse<bool>> DeleteAsync(long id, CancellationToken cancellationToken = default) { var e = await _details.Query(tracking:true).FirstOrDefaultAsync(x => x.Id == id, cancellationToken); if (e == null || e.IsDeleted) { var m = _loc.GetLocalizedString("UserDetailNotFound"); return ApiResponse<bool>.ErrorResult(m,m,404);} e.IsDeleted = true; e.DeletedDate = DateTimeProvider.Now; _details.Update(e); await _uow.SaveChangesAsync(cancellationToken); return ApiResponse<bool>.SuccessResult(true, _loc.GetLocalizedString("UserDetailDeletedSuccessfully")); }
}
