using AutoMapper;
using Microsoft.EntityFrameworkCore;
using Wms.Application.Common;
using Wms.Application.Production.Dtos;
using Wms.Domain.Common;
using Wms.Domain.Entities.Production;

namespace Wms.Application.Production.Services;

public sealed class PrHeaderSerialService : IPrHeaderSerialService
{
    private readonly IRepository<PrHeaderSerial> _serials; private readonly IRepository<PrHeader> _headers; private readonly IUnitOfWork _uow; private readonly IMapper _mapper; private readonly ILocalizationService _loc;
    public PrHeaderSerialService(IRepository<PrHeaderSerial> serials, IRepository<PrHeader> headers, IUnitOfWork uow, IMapper mapper, ILocalizationService loc) { _serials = serials; _headers = headers; _uow = uow; _mapper = mapper; _loc = loc; }
    public async Task<ApiResponse<IEnumerable<PrHeaderSerialDto>>> GetAllAsync(CancellationToken cancellationToken = default) => ApiResponse<IEnumerable<PrHeaderSerialDto>>.SuccessResult(_mapper.Map<List<PrHeaderSerialDto>>(await _serials.Query().ToListAsync(cancellationToken)), _loc.GetLocalizedString("PrHeaderSerialRetrievedSuccessfully"));
    public async Task<ApiResponse<PagedResponse<PrHeaderSerialDto>>> GetPagedAsync(PagedRequest request, CancellationToken cancellationToken = default) { request ??= new(); var q = _serials.Query().ApplyFilters(request.Filters, request.FilterLogic).ApplySorting(request.SortBy ?? "Id", string.Equals(request.SortDirection,"desc",StringComparison.OrdinalIgnoreCase)); var total = await q.CountAsync(cancellationToken); var items = await q.ApplyPagination(request.PageNumber, request.PageSize).ToListAsync(cancellationToken); return ApiResponse<PagedResponse<PrHeaderSerialDto>>.SuccessResult(new(_mapper.Map<List<PrHeaderSerialDto>>(items), total, request.PageNumber < 1 ? 1 : request.PageNumber, request.PageSize < 1 ? 20 : request.PageSize), _loc.GetLocalizedString("PrHeaderSerialRetrievedSuccessfully")); }
    public async Task<ApiResponse<PrHeaderSerialDto>> GetByIdAsync(long id, CancellationToken cancellationToken = default) { var e = await _serials.Query().FirstOrDefaultAsync(x => x.Id == id, cancellationToken); if (e == null || e.IsDeleted) { var m = _loc.GetLocalizedString("PrHeaderSerialNotFound"); return ApiResponse<PrHeaderSerialDto>.ErrorResult(m,m,404);} return ApiResponse<PrHeaderSerialDto>.SuccessResult(_mapper.Map<PrHeaderSerialDto>(e), _loc.GetLocalizedString("PrHeaderSerialRetrievedSuccessfully")); }
    public async Task<ApiResponse<IEnumerable<PrHeaderSerialDto>>> GetByHeaderIdAsync(long headerId, CancellationToken cancellationToken = default) => ApiResponse<IEnumerable<PrHeaderSerialDto>>.SuccessResult(_mapper.Map<List<PrHeaderSerialDto>>(await _serials.Query().Where(x => x.HeaderId == headerId).ToListAsync(cancellationToken)), _loc.GetLocalizedString("PrHeaderSerialRetrievedSuccessfully"));
    public async Task<ApiResponse<PrHeaderSerialDto>> CreateAsync(CreatePrHeaderSerialDto dto, CancellationToken cancellationToken = default) { if (!await _headers.ExistsAsync(dto.HeaderId, cancellationToken)) { var m = _loc.GetLocalizedString("PrHeaderNotFound"); return ApiResponse<PrHeaderSerialDto>.ErrorResult(m,m,400);} var e = _mapper.Map<PrHeaderSerial>(dto); e.CreatedDate = DateTimeProvider.Now; await _serials.AddAsync(e, cancellationToken); await _uow.SaveChangesAsync(cancellationToken); return ApiResponse<PrHeaderSerialDto>.SuccessResult(_mapper.Map<PrHeaderSerialDto>(e), _loc.GetLocalizedString("PrHeaderSerialCreatedSuccessfully")); }
    public async Task<ApiResponse<PrHeaderSerialDto>> UpdateAsync(long id, UpdatePrHeaderSerialDto dto, CancellationToken cancellationToken = default) { var e = await _serials.Query(tracking:true).FirstOrDefaultAsync(x => x.Id == id, cancellationToken); if (e == null || e.IsDeleted) { var m = _loc.GetLocalizedString("PrHeaderSerialNotFound"); return ApiResponse<PrHeaderSerialDto>.ErrorResult(m,m,404);} _mapper.Map(dto,e); e.UpdatedDate = DateTimeProvider.Now; _serials.Update(e); await _uow.SaveChangesAsync(cancellationToken); return ApiResponse<PrHeaderSerialDto>.SuccessResult(_mapper.Map<PrHeaderSerialDto>(e), _loc.GetLocalizedString("PrHeaderSerialUpdatedSuccessfully")); }
    public async Task<ApiResponse<bool>> SoftDeleteAsync(long id, CancellationToken cancellationToken = default) { if (!await _serials.ExistsAsync(id,cancellationToken)) { var m = _loc.GetLocalizedString("PrHeaderSerialNotFound"); return ApiResponse<bool>.ErrorResult(m,m,404);} await _serials.SoftDelete(id, cancellationToken); await _uow.SaveChangesAsync(cancellationToken); return ApiResponse<bool>.SuccessResult(true, _loc.GetLocalizedString("PrHeaderSerialDeletedSuccessfully")); }
}
